apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-dummy
  annotations:
    meta.crossplane.io/maintainer: The Getting Started Organization <support@starter.org>
    meta.crossplane.io/source: github.com/upbound/configuration-scratch
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This starter configuration is completely empty.
    meta.crossplane.io/readme: |
      This starter configuration is completely empty, allowing you to start
      entirely from scratch.
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-dummy
      version: ">=v0.3.0"
