apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrobottriads.dummy.configuration.upbound.io
spec:
  group: dummy.configuration.upbound.io
  names:
    kind: XRobotTriad
    plural: xrobottriads
  claimNames:
    kind: RobotTriad
    plural: robottriads
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              colorFirst:
                type: string
                description: The color of the first robot.
              colorSecond:
                type: string
                description: The color of the second robot.
              colorThird:
                type: string
                description: The color of the third robot.
            required:
            - colorFirst
            - colorSecond
            - colorThird
